# Default configuration for Voxelflex - Medium Settings
input:
  data_dir: /home/s_felix/voxelflex_inputs                    # Base directory for all data files
  voxel_file: /home/s_felix/mdcath-processor-output/voxelized/mdcath_voxelized.hdf5 # Full path to the voxel data
  rmsf_dir: /home/s_felix/mdcath-processor-output/RMSF/replica_average/  # Full path to RMSF data directory
  temperature: 348                          # Temperature identifier: 320, 348, 379, 413, 450, or "average"
  domain_ids: []                            # List of domain IDs to process
  use_metadata: true                        # Flag to include metadata in processing
  max_domains: null                          # Limit to 500 domains for faster training can set to null

output:
  base_dir: outputs/                        # Base output directory
  log_file: voxelflex.log                   # Filename for logging output

model:
  architecture: multipath_rmsf_net          # Choose from: voxelflex_cnn, dilated_resnet3d, multipath_rmsf_net
  input_channels: 5                         # Number of channels: 5 (C, N, O, CA, CB) or 4 if CA/CB are missing
  channel_growth_rate: 1.5                  # Growth rate for channels in the model
  num_residual_blocks: 3                    # Reduced from 4 to 3 for medium settings
  dropout_rate: 0.3                         # Reduced dropout for better convergence
  base_filters: 32                          # Base number of filters for convolutional layers

training:
  batch_size: 256                           # Reduced from 512 to 256 for medium settings
  num_epochs: 10                            # Reduced from 50 to 20 for medium settings
  learning_rate: 0.0005                     # Learning rate for optimizer
  weight_decay: 1e-4                        # Weight decay for regularization
  train_split: 0.7                          # Proportion of data for training
  val_split: 0.15                           # Proportion of data for validation
  test_split: 0.15                          # Proportion of data for testing
  seed: 42                                  # Random seed for reproducibility
  safe_mode: false                          # Enable safe mode for dataset handling (single-threaded)
  memory_efficient: true                    # Use memory-efficient dataset mode
  resume_checkpoint: null                   # Path to checkpoint to resume training from (null = start fresh)
  gradient_clipping:
    enabled: true
    max_norm: 1.0
  warmup:
    enabled: true
    epochs: 1
  domain_streaming:
    enabled: true                           # Enable domain streaming
    initial_domains_per_batch: 150          # Reduced from 200 to 100 for medium settings
    memory_reserve_percent: 25.0            # Increased to 25% to keep more memory free
    dynamic_batch_sizing: true              # Adjust batch size based on memory
  # Mixed precision settings
  mixed_precision:
    enabled: true                           # Enable mixed precision training
    dtype: "bfloat16"                       # Options: "float16", "bfloat16"
  scheduler:                                # Learning rate scheduler configuration
    type: cosine_annealing                  # Scheduler type: reduce_on_plateau, step, or cosine_annealing
    patience: 5                             # Reduced from 10 to 5 for medium settings
    factor: 0.1                             # Factor for scheduler
    mode: min
    T_max: 5                                # Reduced from 10 to 5 for medium settings
    eta_min: 1e-6

prediction:
  domains_per_batch: 150                     # Reduced from 100 to 75 for medium settings
  batch_size: 256                            # Batch size for prediction
  use_training_domains: false                # Use domains from training

logging:
  level: INFO                               # Overall logging level
  console_level: INFO                       # Logging level for console output
  file_level: DEBUG                         # Logging level for file output
  show_progress_bars: true                  # Display progress bars during processing

visualization:
  plot_loss: true                           # Plot training loss over epochs
  plot_predictions: true                    # Plot predicted vs. actual RMSF values
  plot_residue_type_analysis: true          # Analyze prediction errors across residue types
  plot_error_distribution: true             # Visualize overall error distribution
  plot_amino_acid_performance: true         # Generate histogram of prediction errors across amino acids
  save_format: png                          # Format for saving visualizations
  dpi: 300                                  # DPI for saved figures
  plot_correlation: true                    # Plot correlation between predictions and ground truth
  max_scatter_points: 1000                  # Maximum scatter points in plots

system_utilization:
  detect_cores: true                        # Detect available CPU cores
  adjust_for_gpu: true                      # Adjust resources based on GPU availability
  num_workers: 8                           # Reduced from 4 to 16 for medium settings
  memory_ceiling_percent: 80.0              # Reduced from 80.0 to 75.0 for medium settings
  out_of_core_mode: true                    # Use out-of-core processing for large domains
  memory_thresholds:
    warning: 70.0                           # Reduced from 75.0 to 70.0 for earlier warnings
    critical: 80.0                          # Reduced from 85.0 to 80.0 for more headroom
    emergency: 90.0                         # Emergency threshold (percent)
  gpu_memory_fraction: 0.85                 # Reduced from 0.95 to 0.85 to leave more GPU memory free