# Default configuration for Voxelflex
# Default configuration for Voxelflex
input:
  data_dir: /home/s_felix/drFelix/data_full                     # Base directory for all data files
  voxel_file: /home/s_felix/drFelix/data_full/processed/voxelized_output/mdcath_dataset_half_CNOCACB.hdf5   # Full path to the voxel data
  rmsf_dir: /home/s_felix/drFelix/data_full/processed/RMSF/replicas  # Full path to RMSF data directory
  temperature: 320                          # Temperature identifier: 320, 348, 379, 413, 450, or "average"
  domain_ids: [1a02F00]                            # List of domain IDs to process
  use_metadata: true                        # Flag to include metadata in processing                     # Flag to include metadata in processing

output:
  base_dir: outputs/                        # Base output directory
  log_file: voxelflex.log                   # Filename for logging output

model:
  architecture: voxelflex_cnn            # Choose from: voxelflex_cnn, dilated_resnet3d, multipath_rmsf_net
  input_channels: 5                         # Number of channels: 5 (C, N, O, CA, CB) or 4 if CA/CB are missing
  channel_growth_rate: 1.5                  # Growth rate for channels in the model
  num_residual_blocks: 4                    # Number of residual blocks in the CNN
  dropout_rate: 0.3                         # Dropout rate for regularization
  base_filters: 32                          # Base number of filters for convolutional layers

training:
  batch_size: 32                            # Training batch size
  num_epochs: 5                           # Number of training epochs
  learning_rate: 0.001                      # Learning rate for optimizer
  weight_decay: 1e-5                        # Weight decay for regularization
  train_split: 0.7                          # Proportion of data for training
  val_split: 0.15                           # Proportion of data for validation
  test_split: 0.15                          # Proportion of data for testing
  seed: 42                                  # Random seed for reproducibility
  scheduler:                                # Learning rate scheduler configuration
    type: reduce_on_plateau                 # Scheduler type: reduce_on_plateau or step
    patience: 10                            # Patience for ReduceLROnPlateau
    factor: 0.1                             # Factor for scheduler
    mode: min                               # Mode for ReduceLROnPlateau: min or max

logging:
  level: INFO                               # Overall logging level
  console_level: INFO                       # Logging level for console output
  file_level: DEBUG                         # Logging level for file output
  show_progress_bars: true                  # Display progress bars during processing

visualization:
  plot_loss: true                           # Plot training loss over epochs
  plot_predictions: true                    # Plot predicted vs. actual RMSF values
  plot_residue_type_analysis: true          # Analyze prediction errors across residue types
  plot_error_distribution: true             # Visualize overall error distribution
  plot_amino_acid_performance: true         # Generate histogram of prediction errors across amino acids
  save_format: png                          # Format for saving visualizations
  dpi: 300                                  # DPI for saved figures
  plot_correlation: true                    # Plot correlation between predictions and ground truth
  max_scatter_points: 1000                  # Maximum scatter points in plots

system_utilization:
  detect_cores: true                        # Enable detection of CPU cores for multiprocessing
  adjust_for_gpu: true                      # Adjust processing based on GPU availability
  num_workers: 10                            # Number of worker processes for DataLoaders